tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "git"
brew "mas"
brew "pyenv"
cask "docker"
cask "google-chrome"
cask "istat-menus"
cask "notion"
cask "pycharm"
cask "slack"
cask "visual-studio-code"
cask "warp"
mas "KakaoTalk", id: 869223134
mas "Magnet", id: 441258766
