tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "iterm2"
cask "istat-menus"
cask "google-chrome"
brew "git"
brew "mas"
mas "Magnet", id: 441258766
cask "docker"
cask "notion"
cask "pycharm"
cask "slack"
cask "visual-studio-code"
mas "KakaoTalk", id: 869223134
brew "awscli"
brew "maccy"
